name: Test

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.2', '8.3', '8.4' ]
        composer-flag: [ '', '--prefer-lowest' ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer update ${{ matrix.composer-flag }}

      - name: Run tests
        run: composer test